
CREATE TABLE `SimulationActors` (
  `SimulationActorId` int(10) UNSIGNED NOT NULL,
  `SimulationId` int(10) UNSIGNED NOT NULL,
  `CharacterId` int(10) UNSIGNED DEFAULT NULL,
  `CharacterJSON` text,
  `ClassId` tinyint(3) UNSIGNED NOT NULL,
  `SpecializationId` smallint(5) UNSIGNED NOT NULL,
  `RaceId` tinyint(3) UNSIGNED NOT NULL,
  `Gender` tinyint(3) UNSIGNED NOT NULL,
  `Level` tinyint(3) UNSIGNED NOT NULL,
  `ThumbnailURL` varchar(255) DEFAULT NULL,
  `CalcTalent` varchar(7) DEFAULT NULL,
  `CalcGlyph` varchar(6) DEFAULT NULL,
  `ItemLevel` smallint(5) UNSIGNED DEFAULT NULL,
  `DPS` int(10) UNSIGNED DEFAULT NULL,
  `ScalePrimaryStat` float DEFAULT NULL,
  `ScaleStamina` float DEFAULT NULL,
  `ScaleSpirit` float DEFAULT NULL,
  `ScaleSpellPower` float DEFAULT NULL,
  `ScaleAttackPower` float DEFAULT NULL,
  `ScaleCrit` float DEFAULT NULL,
  `ScaleHaste` float DEFAULT NULL,
  `ScaleMastery` float DEFAULT NULL,
  `ScaleVersatility` float DEFAULT NULL,
  `ScaleMultistrike` float DEFAULT NULL,
  `ScaleWeaponDPS` float DEFAULT NULL,
  `ScaleOffhandWeaponDPS` float DEFAULT NULL,
  `ScaleArmor` float DEFAULT NULL,
  `ScaleBonusArmor` float DEFAULT NULL,
  `ScaleAvoidance` float DEFAULT NULL,
  `ScaleLeech` float DEFAULT NULL,
  `ScaleMovementSpeed` float DEFAULT NULL,
  `ArmorySpec` varchar(8) DEFAULT 'active',
  `SimulationRole` varchar(4) DEFAULT 'DPS',
  `TMI` int(10) UNSIGNED DEFAULT NULL,
  `DTPS` int(10) UNSIGNED DEFAULT NULL,
  `HPS` int(10) UNSIGNED DEFAULT NULL,
  `APS` int(10) UNSIGNED DEFAULT NULL,
  `SimTalent` varchar(7) DEFAULT NULL,
  `Talent1Id` int(11) UNSIGNED DEFAULT NULL,
  `Talent2Id` int(11) UNSIGNED DEFAULT NULL,
  `Talent3Id` int(11) UNSIGNED DEFAULT NULL,
  `Talent4Id` int(11) UNSIGNED DEFAULT NULL,
  `Talent5Id` int(11) UNSIGNED DEFAULT NULL,
  `Talent6Id` int(11) UNSIGNED DEFAULT NULL,
  `Talent7Id` int(11) UNSIGNED DEFAULT NULL,
  `IsCustomActor` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `CustomActorName` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
